// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbnQuejh5ySROPrz96ciHWC4VT5zViDqY',
    appId: '1:330087111960:web:6105b6b0724bcb58d1926d',
    messagingSenderId: '330087111960',
    projectId: 'sentri-app-5f047',
    authDomain: 'sentri-app-5f047.firebaseapp.com',
    storageBucket: 'sentri-app-5f047.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWCKsxB0-nB5EBQWsAplG0iUjmxrb0fQ',
    appId: '1:330087111960:ios:2de49a76f1a1abf7d1926d',
    messagingSenderId: '330087111960',
    projectId: 'sentri-app-5f047',
    storageBucket: 'sentri-app-5f047.firebasestorage.app',
    iosClientId: '330087111960-325oudq11ih8fc826h4jkjkjkir2rs4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentriApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWCKsxB0-nB5EBQWsAplG0iUjmxrb0fQ',
    appId: '1:330087111960:ios:2de49a76f1a1abf7d1926d',
    messagingSenderId: '330087111960',
    projectId: 'sentri-app-5f047',
    storageBucket: 'sentri-app-5f047.firebasestorage.app',
    iosClientId: '330087111960-325oudq11ih8fc826h4jkjkjkir2rs4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbnQuejh5ySROPrz96ciHWC4VT5zViDqY',
    appId: '1:330087111960:web:0bd37e4f8317a225d1926d',
    messagingSenderId: '330087111960',
    projectId: 'sentri-app-5f047',
    authDomain: 'sentri-app-5f047.firebaseapp.com',
    storageBucket: 'sentri-app-5f047.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH9uv_aFVAtrCx_gYYEsmeILXLzxUvRjg',
    appId: '1:330087111960:android:26fddfc6eb6aa2add1926d',
    messagingSenderId: '330087111960',
    projectId: 'sentri-app-5f047',
    storageBucket: 'sentri-app-5f047.firebasestorage.app',
  );
}
